# Generated by Django 5.2.7 on 2025-10-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('Categoria_Id', models.IntegerField(db_column='CATEGORIA_ID', primary_key=True, serialize=False)),
                ('Nombre_Categoria', models.CharField(db_column='NOMBRE_CATEGORIA', max_length=250)),
            ],
            options={
                'db_table': 'CATEGORIAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('Devolucion_Id', models.IntegerField(db_column='DEVOLUCION_ID', primary_key=True, serialize=False)),
                ('Fecha_Devolucion', models.DateField(db_column='FECHA_DEVOLUCION')),
                ('Hora_Devolucion', models.DateTimeField(db_column='HORA_DEVOLUCION')),
                ('Observaciones_Devolucion', models.CharField(db_column='OBSERVACIONES_DEVOLUCION', max_length=600)),
            ],
            options={
                'db_table': 'DEVOLUCIONES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('Entrega_Id', models.IntegerField(db_column='ENTREGA_ID', primary_key=True, serialize=False)),
                ('Fecha_Entrega', models.DateField(db_column='FECHA_ENTREGA')),
                ('Hora_Entrega', models.DateTimeField(db_column='HORA_ENTREGA')),
                ('Observacion_Entrega', models.CharField(db_column='OBSERVACION_ENTREGA', max_length=600)),
            ],
            options={
                'db_table': 'ENTREGAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('Estado_Id', models.IntegerField(db_column='ESTADO_ID', primary_key=True, serialize=False)),
                ('Nombre_Estado', models.CharField(db_column='NOMBRE_ESTADO', max_length=80)),
                ('Descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=250, null=True)),
            ],
            options={
                'db_table': 'ESTADOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('Facultad_Id', models.IntegerField(db_column='FACULTAD_ID', primary_key=True, serialize=False)),
                ('Nombre_Facultad', models.CharField(db_column='NOMBRE_FACULTAD', max_length=80)),
            ],
            options={
                'db_table': 'FACULTADES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Frecuencia_Servicio',
            fields=[
                ('Frecuencia_Servicio_Id', models.IntegerField(db_column='FRECUENCIA_SERVICIO_ID', primary_key=True, serialize=False)),
                ('Nombre_Frecuencia_Servicio', models.CharField(db_column='NOMBRE_FRECUENCIA_SERVICIO', max_length=80)),
            ],
            options={
                'db_table': 'FRECUENCIA_SERVICIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorariosLaboratorio',
            fields=[
                ('Horario_Id', models.AutoField(db_column='HORARIO_ID', primary_key=True, serialize=False)),
                ('Dia_Semana', models.CharField(db_column='DIA_SEMANA', max_length=15)),
                ('Hora_Inicio', models.TimeField(db_column='HORA_INICIO')),
                ('Hora_Fin', models.TimeField(db_column='HORA_FIN')),
            ],
            options={
                'db_table': 'HORARIOS_LABORATORIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('Laboratorio_Id', models.AutoField(db_column='LABORATORIO_ID', primary_key=True, serialize=False)),
                ('Nombre_Laboratorio', models.CharField(db_column='NOMBRE_LABORATORIO', max_length=100)),
                ('Capacidad', models.IntegerField(db_column='CAPACIDAD')),
                ('Ubicacion', models.CharField(db_column='UBICACION', max_length=50)),
            ],
            options={
                'db_table': 'LABORATORIOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objetos',
            fields=[
                ('Objetos_Id', models.IntegerField(db_column='OBJETOS_ID', primary_key=True, serialize=False)),
                ('Nombre_Objetos', models.CharField(db_column='NOMBRE_OBJETOS', max_length=80)),
                ('Descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=250, null=True)),
                ('Cant_Stock', models.IntegerField(blank=True, db_column='CANT_STOCK', null=True)),
            ],
            options={
                'db_table': 'OBJETOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('Programa_Id', models.IntegerField(db_column='PROGRAMA_ID', primary_key=True, serialize=False)),
                ('Nombre_Programa', models.CharField(db_column='NOMBRE_PROGRAMA', max_length=80)),
            ],
            options={
                'db_table': 'PROGRAMAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('Rol_Id', models.IntegerField(db_column='ROL_ID', primary_key=True, serialize=False)),
                ('Nombre_Roles', models.CharField(db_column='NOMBRE_ROLES', max_length=80)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'ROLES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Identificacion',
            fields=[
                ('Tipo_Id', models.IntegerField(db_column='TIPO_ID', primary_key=True, serialize=False)),
                ('Nombre_Tipo_Identificacion', models.CharField(db_column='NOMBRE_TIPO_IDENTIFICACION', max_length=80)),
            ],
            options={
                'db_table': 'TIPO_IDENTIFICACION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Servicio',
            fields=[
                ('Tipo_Servicio_Id', models.IntegerField(db_column='TIPO_SERVICIO_ID', primary_key=True, serialize=False)),
                ('Nombre_Tipo_Servicio', models.CharField(db_column='NOMBRE_TIPO_SERVICIO', max_length=80)),
            ],
            options={
                'db_table': 'TIPO_SERVICIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Solicitantes',
            fields=[
                ('Solicitante_Id', models.IntegerField(db_column='SOLICITANTE_ID', primary_key=True, serialize=False)),
                ('Nombre_Solicitante', models.CharField(db_column='NOMBRE_SOLICITANTE', max_length=80)),
            ],
            options={
                'db_table': 'TIPO_SOLICITANTES',
                'managed': False,
            },
        ),
    ]
