# Generated by Django 5.2.7 on 2025-11-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios_Laboratorio',
            fields=[
                ('Horario_Id', models.IntegerField(db_column='HORARIO_ID', primary_key=True, serialize=False)),
                ('Dia_Semana', models.CharField(db_column='DIA_SEMANA', max_length=20)),
                ('Hora_Inicio', models.DateTimeField(db_column='HORA_INICIO')),
                ('Hora_Fin', models.DateTimeField(db_column='HORA_FIN')),
            ],
            options={
                'db_table': 'HORARIOS_LABORATORIO',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='HorariosLaboratorio',
        ),
    ]
