# Generated by Django 5.2.7 on 2025-11-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante_Solicitud',
            fields=[
                ('Usuario_Solicitud_Id', models.DecimalField(db_column='USUARIO_SOLICITUD_ID', decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Integrantes de Solicitud',
                'db_table': 'USUARIO_SOLICITUD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('Solicitud_Id', models.AutoField(db_column='SOLICITUD_ID', primary_key=True, serialize=False)),
                ('Fecha_solicitud', models.DateField(db_column='FECHA_SOLICITUD')),
                ('Asignatura', models.CharField(db_column='ASIGNATURA', max_length=100)),
                ('N_asistentes', models.IntegerField(db_column='N_ASISTENTES')),
                ('Fecha_Inicio', models.DateField(blank=True, db_column='FECHA_INICIO', null=True)),
                ('Fecha_Fin', models.DateField(blank=True, db_column='FECHA_FIN', null=True)),
                ('Hora_Inicio', models.DateTimeField(blank=True, db_column='HORA_INICIO', null=True)),
                ('Hora_Fin', models.DateTimeField(blank=True, db_column='HORA_FIN', null=True)),
                ('Observaciones_Solicitud', models.TextField(blank=True, db_column='OBSERVACIONES_SOLICITUD', null=True)),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Servicio/Objeto',
                'db_table': 'SOLICITUDES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudes_Detalle',
            fields=[
                ('Detalle_Id', models.AutoField(db_column='DETALLE_ID', primary_key=True, serialize=False)),
                ('Nombre_Detalle', models.CharField(db_column='NOMBRE_DETALLE', max_length=100)),
                ('Valor', models.CharField(db_column='VALOR', max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Detalles de Solicitud',
                'db_table': 'SOLICITUDES_DETALLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudes_Objetos',
            fields=[
                ('Solicitud_Objetos_Id', models.AutoField(db_column='SOLICITUD_OBJETOS_ID', primary_key=True, serialize=False)),
                ('Cantidad_Objetos', models.IntegerField(db_column='CANTIDAD_OBJETOS')),
            ],
            options={
                'verbose_name_plural': 'Objetos Solicitados',
                'db_table': 'SOLICITUDES_OBJETOS',
                'managed': False,
            },
        ),
    ]
