# Generated by Django 5.2.7 on 2025-10-17 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Usuario_Id', models.OneToOneField(db_column='USUARIO_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Nombres', models.CharField(db_column='NOMBRES', max_length=100)),
                ('Apellido1', models.CharField(db_column='APELLIDO1', max_length=50)),
                ('Apellido2', models.CharField(blank=True, db_column='APELLIDO2', max_length=50, null=True)),
                ('Correo_electronico', models.CharField(blank=True, db_column='CORREO_ELECTRONICO', max_length=250, null=True)),
                ('Direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=250, null=True)),
                ('Telefono', models.DecimalField(blank=True, db_column='TELEFONO', decimal_places=0, max_digits=15, null=True)),
                ('Numero_celular', models.DecimalField(blank=True, db_column='NUMERO_CELULAR', decimal_places=0, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario (Oracle)',
                'verbose_name_plural': 'Perfiles de Usuarios (Oracle)',
                'db_table': 'USUARIOS',
                'managed': False,
            },
        ),
    ]
