# Generated by Django 5.2.7 on 2025-11-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios_Programas',
            fields=[
                ('Usuario_Id', models.ForeignKey(db_column='USUARIO_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='programas_asociados', serialize=False, to='usuarios.usuarios')),
            ],
            options={
                'verbose_name': 'Programa de Usuario (Oracle)',
                'verbose_name_plural': 'Programas de Usuarios (Oracle)',
                'db_table': 'USUARIOS_PROGRAMAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios_Roles',
            fields=[
                ('Usuario_Id', models.ForeignKey(db_column='USUARIO_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='roles_usuario_detalle', serialize=False, to='usuarios.usuarios')),
            ],
            options={
                'verbose_name': 'Rol de Usuario (Oracle)',
                'verbose_name_plural': 'Roles de Usuarios (Oracle)',
                'db_table': 'USUARIOS_ROLES',
                'managed': False,
            },
        ),
    ]
